name: adopt-env
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.10.10
  - setuptools
#  - pip:
#      - google-vizier
#      - jax
#      - jaxlib
#      - numpy
#      - opt-einsum
#      - ray
