name: Ruff Linting
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: '--config=./pyproject.toml'
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.0.259
